apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::569460721785:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-129H2AHWO5TRY
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::569460721785:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-04T19:29:22Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1634"
  uid: 9b16e5da-f5a2-4179-b665-9f7c2735486d
